//------------------------------------------------------------------------------
// <auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using III.Domain.Common;

namespace ESEIM.Models
{
    [Table("LMS_LECTURE_MANAGEMENT")]
    public class LmsLectureManagement : IPurchasableObject, StringExtensions.IEntity<int>
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string LectName { get; set; }
        public string LectCode { get; set; }
        public string LectDescription { get; set; }
        public int? Duration { get; set; }
        public string Status { get; set; }
        public string Unit { get; set; }
        public string SubjectCode { get; set; }
        public string VideoPresent { get; set; }
        public string Share { get; set; }
        public string VideosDuration
        {
            get
            {
                return JsonConvert.SerializeObject(ListVideoDuration);
            }
            set
            {
                ListVideoDuration = string.IsNullOrEmpty(value)
                ? new List<VideoDuration>()
                : JsonConvert.DeserializeObject<List<VideoDuration>>(value);
            }
        }
        [NotMapped]
        public List<VideoDuration> ListVideoDuration { get; set; }
        public string Level { get; set; }
        public string Rating { 
            get => JsonConvert.SerializeObject(ListRating);
            set =>
                ListRating = string.IsNullOrEmpty(value)
                    ? new List<LmsPracticeRating>()
                    : JsonConvert.DeserializeObject<List<LmsPracticeRating>>(value);
        }
        [NotMapped]
        public List<LmsPracticeRating> ListRating { get; set; }
        public bool? IsInteractive { get; set; }
        public string InteractiveFilePath { get; set; }
        public decimal? Price { get; set; }
        [NotMapped]
        public bool? IsPurchased { get; set; }
        public string JsonTutor888 { get; set; }
        public bool? IsTutor888 { get; set; }
        public string AnswerTutor888 { get; set; }
    }
    public class VideoDuration
    {
        public string VideoFileCode { get; set; }
        public int Duration { get; set; }
    }
}

